// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TenantsDBContext))]
    [Migration("20241119125543_InitialCreateTenantDB")]
    partial class InitialCreateTenantDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DBPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DBUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrustedConnection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrusServerCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatabaseName = "VentionBankDB",
                            IsTrustedConnection = false,
                            Name = "DefaultConnectionString",
                            Server = ".",
                            TrusServerCertificate = false
                        },
                        new
                        {
                            Id = 2,
                            DBPassword = "#Include <stdio.h>",
                            DBUser = "sa",
                            DatabaseName = "BankDB1",
                            IsTrustedConnection = false,
                            Name = "Customer1",
                            Server = "local",
                            TrusServerCertificate = false
                        },
                        new
                        {
                            Id = 3,
                            DBPassword = "#Lithu@nia&Baltic$>",
                            DBUser = "sa",
                            DatabaseName = "BkDB2",
                            IsTrustedConnection = false,
                            Name = "Customer2",
                            Server = ".",
                            TrusServerCertificate = true
                        },
                        new
                        {
                            Id = 4,
                            DBPassword = "P@$$w0rd!",
                            DBUser = "sa",
                            DatabaseName = "BankDB3",
                            IsTrustedConnection = false,
                            Name = "Customer3",
                            Server = ".",
                            TrusServerCertificate = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
