// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TenantsDBContext))]
    partial class TenantsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DBConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DBConnectionString = "Server=.;Database=BankDB;Trusted_Connection=True;TrustServerCertificate=True;",
                            Name = "DefaultConnectionString"
                        },
                        new
                        {
                            Id = 2,
                            DBConnectionString = "Server=.;Database=BankDB1;Trusted_Connection=True;TrustServerCertificate=True;",
                            Name = "Customer1"
                        },
                        new
                        {
                            Id = 3,
                            DBConnectionString = "Server=.;Database=BankDB2;Trusted_Connection=True;TrustServerCertificate=True;",
                            Name = "Customer2"
                        },
                        new
                        {
                            Id = 4,
                            DBConnectionString = "Server=.;Database=BankDB3;Trusted_Connection=True;TrustServerCertificate=True;",
                            Name = "Customer3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
